### ISSUE TITLE
Branch protections for ACCESS-ESM1.5 branch

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/MOM5#15]
Given the [spack package for the ACCESS-ESM1.5 MOM5 build will utilise a special branch on this repo](https://github.com/ACCESS-NRI/spack-packages/issues/104#issuecomment-2097281368), that branch should be protected.

See https://github.com/ACCESS-NRI/MOM5/issues/2

**Comment by CodeGat** [comment]
Protected both `master` and `access-esm1.5`, see https://github.com/ACCESS-NRI/MOM5/settings/branches
