### ISSUE TITLE
ACCESS-ESM version in repo

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/MOM5#2]
Need to have the version of MOM5 used in ACCESS-ESM publicly accessible in GitHub repo

Need to 

- identify code used
- use tool to export svn branch to git
- push to this repository

There was an existing attempt to harmonise the ACCESS-ESM-1.5 MOM version in this repo https://github.com/mom-ocean/MOM5/tree/esm-harmonised

**Comment by penguian** [comment]
@aidanheerdegen See the `access-esm1.5` branch. Can this issue be closed?
