### ISSUE TITLE
Need CI build checks added to access-esm1.5 branch

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/MOM5#23]
The `access-esm1.5` branch contains the code used for the ACCESS-ESM1.5 model as used in CMIP6. It differs from `main` and we need CI compilation checks in case we back-port fixes to it, like this:

https://github.com/ACCESS-NRI/MOM5/pull/22#issuecomment-2205144448

**Comment by CodeGat** [comment]
I'M ON IT, CAPTAIN :pirate_flag:
