### ISSUE TITLE
Add compilation CI to MOM5

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/MOM5#3]
Add compilation CI on GitHub

**Comment by harshula** [comment]
`mom5` still has ``set new_hash=`git rev-parse HEAD` `` in `exp/update_version.csh`
So, a compile from a tarball may fail at the moment.

**Comment by harshula** [comment]
Issue https://github.com/ACCESS-NRI/MOM5/issues/4 "Stop running git commands during the build process"

**Comment by harshula** [comment]
NOTE: MOM5 requires `csh` and `sed` in the build environment.
