### ISSUE TITLE
Have an option to not run git commands during the build process

### ISSUE THREAD

**Issue by harshula** [ACCESS-NRI/MOM5#4]
`exp/MOM_compile.csh` calls `exp/version_compile.csh` and that calls `exp/update_version.csh`

 `exp/update_version.csh`:
```
set old_hash=`grep 'public :: MOM_COMMIT_HASH' ../src/version/version.F90 | cut -d '"' -f 2 | cut -d '=' -f 2`
set new_hash=`git rev-parse HEAD`
```

**Comment by harshula** [comment]
This commit in the development branch removes git execution during the build: https://github.com/ACCESS-NRI/MOM5/commit/926d370ff03ffcb90d4271c9cc2c9fb06db9d28c

**Comment by harshula** [comment]
The development branch commit has been accidentally merged to main via PR https://github.com/ACCESS-NRI/MOM5/pull/6/

**Comment by aidanheerdegen** [comment]
There is a related issue on the upstream https://github.com/mom-ocean/MOM5/issues/308

I will put in a fix there and rebase/merge those changes into our fork.

**Comment by aidanheerdegen** [comment]
This is the upstream PR

https://github.com/mom-ocean/MOM5/pull/384

**Comment by harshula** [comment]
Commit https://github.com/ACCESS-NRI/MOM5/commit/d7ba13a3f364ce130b6ad0ba813f01832cada7a2
